openapi: 3.0.0
info:
  title: 06-Jobs-API
  version: 1.0.0
servers:
  - url: http://localhost:3000/api/v1
  - url: https://jobs-api-up2code3.onrender.com/api/v1

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      
      
paths:


  /auth/register:
  
  
    post:
      tags:
        - User
      summary: Register
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                name: Charlie2
                email: Charlie2@mail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
            
  /auth/login:
  
  
    post:
      tags:
        - User
      summary: Log in
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                email: Mary@mail.com
                password: '123456'
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
            
  /jobs:
  
  
    post:
      tags:
        - Jobs
      summary: Create Job
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Gas
                position: Clerk
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
            
    get:
      tags:
        - Jobs
      summary: Get All Jobs
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
            
  /jobs/{id}:
  
  
    get:
      tags:
        - Jobs
      summary: Get Single Job
      parameters:
      - in: path
        name: id
        schema:
         type: string
        required: true
        description: The Job ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}
            
            
    patch:
      tags:
        - Jobs
      summary: Update Job
      parameters:
      - in: path
        name: id
        schema:
         type: string
        required: true
        description: The Job ID
      requestBody:
        content:
          application/json:
            schema:
              type: object
              example:
                company: Pizza
                position: Oven
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          
          
    delete:
      tags:
        - Jobs
      summary: Delete Job
      parameters:
      - in: path
        name: id
        schema:
         type: string
        required: true
        description: The Job ID
      security:
        - bearerAuth: []
      responses:
        '200':
          description: Successful response
          content:
            application/json: {}

